### ISSUE TITLE
Not working in Node 5?

### ISSUE THREAD

**Issue by deepfriedmind** [tjunnone/npm-check-updates#165]
When running `ncu` I get the following error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'config-chain'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/config/core.js:1:72)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/npm.js:22:17
    at Object.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/npm/lib/npm.js:483:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
```

It works fine in Node 4.2.2.

**Comment by deepfriedmind** [comment]
Never mind. It works now after some fiddling around with nvm/npm (although I have no idea what was the actual solution).

**Comment by rjfranco** [comment]
I'm running into this now and can't seem to get around it, would you mind telling me what version of npm you are using @deepfriedmind ?
